name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.3'
          arch: win64_msvc2022_64
          cache: true

      - name: Configure
        run: cmake --preset windows-msvc-debug

      - name: Build
        run: cmake --build --preset windows-msvc-debug

      - name: Test
        run: ctest --preset windows-msvc-debug
